In [1]:
n = 9 
v = 10
print(v+n)

19


In [2]:
! pip list

Package             Version

You should consider upgrading via the 'c:\users\lenovo\onedrive\desktop\7th semester\cs2_ai\jupyter_labs\env\scripts\python.exe -m pip install --upgrade pip' command.



------------------- -------
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.3.0
backcall            0.2.0
bleach              3.3.0
cffi                1.14.5
colorama            0.4.4
decorator           4.4.2
defusedxml          0.7.1
entrypoints         0.3
ipykernel           5.5.0
ipython             7.21.0
ipython-genutils    0.2.0
jedi                0.18.0
Jinja2              2.11.3
jsonschema          3.2.0
jupyter-client      6.1.12
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
MarkupSafe          1.1.1
mistune             0.8.4
nbclient            0.5.3
nbconvert           6.0.7
nbformat            5.1.2
nest-asyncio        1.5.1
notebook            6.3.0
packaging           20.9
pandocfilters       1.4.3
parso               0.8.1
pickleshare         0.7.5
pip                 20.2.3
prometheus-client   0.9.0
prompt-toolkit      3.0.18
pycparser           2.20
Pygments            2.8.1
pyparsing           2.4.7
pyrsistent          0.17.3
pyth

In [4]:
%pwd


'C:\\Users\\lenovo\\OneDrive\\Desktop\\7th Semester\\CS2_AI\\Jupyter_Labs'

In [31]:
%%HTML
'<iframe width="450" height="315" 
src="https://www.youtube.com/embed/lTIeZ2ahEkQ" frameborder="0" allowfullscreen></iframe>'

In [2]:
%%timeit

square_error = [x*x for x in range(50)]
loop2 = [x for x in range(20)]

4.78 µs ± 430 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
import numpy as np

a = np.array([2,3,4])
print(a)
print(type(a))
print(a.shape)

print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],
              [4,5,6]])
print(b)
print(b.shape)
print(b[0,0], b[0,1], b[1,1], b[1,2])



[2 3 4]
<class 'numpy.ndarray'>
(3,)
2 3 4
[5 3 4]
[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 5 6


In [6]:
import numpy as np

a = np.zeros((3,3))
print(a)

b = np.ones((2,4))
print(b)

c = np.full((4,4),5)
print(c)

d = np.eye(3)
print(d)

e = np.random.random((3,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.34046349 0.28423498 0.0014099 ]
 [0.60781315 0.44388856 0.64163965]
 [0.93025134 0.84879923 0.02199659]]


In [8]:
import numpy as np

original = np.array([1,2,3])
new = original
new[2] = 0
print(original)
print(new)

new = np.copy(original)
new[1] = 5
print(original)
print(new)

[1 2 0]
[1 2 0]
[1 2 0]
[1 5 0]


In [12]:
#slicing
import numpy as np
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print(a)

b = a[:2, 1:3]
print(b)

print(a[0,2])
b[0,1] = 0
print(b)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
3
[[2 0]
 [6 7]]
[[ 1  2  0  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
import numpy as np
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print(a)

b = np.array([1,2,0])
print(np.arange(3))

print(a[np.arange(3), b])

a[np.arange(3), b] +=5
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 7 9]
[[ 1  7  3  4]
 [ 5  6 12  8]
 [14 10 11 12]]


In [29]:
import numpy as np

a = np.arange(2*3*4).reshape(4,3,2)
print(a, "\n")
print("shape of a is:", a.shape, "\n")

print(a[:,:,0], "\n\n", a[:,:,1], "\n")

b = a.ravel()
print(b, b.shape, "\n")

c = a.reshape(1,-1)
print(c, c.shape, "\n")

print("SWAPPING...")
d = a.swapaxes(1,2)
print(d[:,:,0], "\n\n", d[:,:,1], "\n\n", d[:,:,2], "\n")

e = d.ravel()
print(e, e.shape, "\n")

print("RESHAPING...")
d = a.reshape(4,2,3)
print(d[:,:,0], "\n\n", d[:,:,1], "\n\n", d[:,:,2], "\n")

e = d.ravel()
print(e, e.shape, "\n")

print("TRANSPOSE...")
d = a.transpose(2,1,0)
print(d[:,:,0], "\n\n", d[:,:,1], "\n\n", d[:,:,2], "\n")

e = d.ravel()
print(e, e.shape, "\n")


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]] 

shape of a is: (4, 3, 2) 

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]] 

 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] (24,) 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]] (1, 24) 

SWAPPING...
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]] 

 [[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]] 

 [[ 4  5]
 [10 11]
 [16 17]
 [22 23]] 

[ 0  2  4  1  3  5  6  8 10  7  9 11 12 14 16 13 15 17 18 20 22 19 21 23] (24,) 

RESHAPING...
[[ 0  3]
 [ 6  9]
 [12 15]
 [18 21]] 

 [[ 1  4]
 [ 7 10]
 [13 16]
 [19 22]] 

 [[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] (24,) 

TRANSPOSE...
[[0 2 4]
 [1 3 5]] 

 [[ 6  8 10]
 [ 7  9 11]] 

 [[12 14 16]
 [13 15 17]] 

[ 0  6 12 18  2  8 14 20  4 10 16 22  1  7 13 19  3  9 