In [1]:
from sklearn import datasets
from matplotlib import pyplot as plt
import numpy as np
import numpy.matlib

In [2]:
X = np.array([[0.5, 0.7, 0.2],[0.4, 0.1, 0.5]])
W1 = np.array([[0.2, 0.15],[0.1, 0.2]])
j = np.array([0.5,0.8])
b = np.array([0.2,0.1])
W2 = np.array([0.3, 0.7])
y = np.array([0.6, 0.3, 0.4])

rate = 0.5
M = 3

# Normalizing input
d11 = X[0,:] - np.mean(X[0,:])
d12 = np.std(X[0,:])
d21= X[1,:] - np.mean(X[1,:])
d22 = np.std(X[1,:])
XNorm0 = np.array([d11/ d12, d21/ d22]); 
print ("Normalized Input: ", XNorm0)

Normalized Input:  [[ 0.16222142  1.13554995 -1.29777137]
 [ 0.39223227 -1.37281295  0.98058068]]


In [3]:
for i in range(0,3):
    print("\n\nIteration: ", i)
    z1 =  W1 @ XNorm0 # Calculate 1st layer output
    z1Norm0 = np.array([(z1[0,:] - np.mean(z1[0,:])) / np.std(z1[0,:]), (z1[1,:] - np.mean(z1[1,:])) / np.std(z1[1,:])])  # Normalize 1st layer output
    zBatch = np.array([(np.dot(j[0], z1Norm0[0,:]) + b[0]), (np.dot(j[1], z1Norm0[1,:]) + b[1])])  # Calculate batch layer output
    a = zBatch
    a = np.where(a<0, 0, a)

    yhat = W2 @ a  # Calculate last layer output
    loss = np.sum((yhat-y)**2)  # Calculate loss
    print("Loss: ", loss )

    # backprop
    dJdYhat = -2*(y-yhat)
    dYdw2 = a.transpose()
    dJdw2 =  dJdYhat @ dYdw2  

    dYda = np.matlib.repmat(W2.transpose(), M, 1) 
    dadzBatch = np.ones(np.shape(zBatch))
    dadzBatch = np.where(zBatch<0, 0, zBatch)
    dadzBatch = np.reshape(dadzBatch, np.shape(zBatch))
    dJdzBatch = np.matlib.repmat(dJdYhat, np.shape(W2)[0], 1) @ dYda @ dadzBatch
    # print("dJdzBatch: ", dJdzBatch)

    dzBatchdj = z1Norm0;
    dJdj = np.sum(dJdzBatch*dzBatchdj, 1);

    dJdb = np.sum(dJdzBatch*1, 1);

    dzBatchdzNorm = np.matlib.repmat(j, M, 1)
    dzNormdz = np.matlib.repmat([1/np.std(z1[0,:]), 1/np.std(z1[1,:])], M, 1).transpose() 
    dJdz = np.dot(np.dot(dJdzBatch, dzBatchdzNorm), dzNormdz) 

    dzdw1 = XNorm0.transpose();
    dJdw1 = np.dot(dJdz, dzdw1);
    
    W2 = W2-rate*dJdw2
    print("W2: ", W2)
    j = j-rate*dJdj
    print("j: ", j)
    b = b-rate*dJdb
    print("b: ", b)
    W1 = W1-rate*dJdw1
    print("W1: \n", W1)
    



Iteration:  0
Loss:  0.06510139064623763
W2:  [0.25094962 0.58473823]
j:  [0.5165358  0.83759705]
b:  [0.26548318 0.16548318]
W1: 
 [[0.2  0.15]
 [0.1  0.2 ]]


Iteration:  1
Loss:  0.052510479170636594
W2:  [0.24091391 0.50412545]
j:  [0.54818513 0.91210164]
b:  [0.39814619 0.29814619]
W1: 
 [[0.2  0.15]
 [0.1  0.2 ]]


Iteration:  2
Loss:  0.058158580548700683
W2:  [0.16490216 0.31202441]
j:  [0.54351943 0.90156518]
b:  [0.37825089 0.27825089]
W1: 
 [[0.2  0.15]
 [0.1  0.2 ]]
